### ISSUE TITLE
В Overleaf страницы нумеруются римскими цифрами

### ISSUE THREAD

**Issue by altavir** [yl3dy/mipt-thesis#6]

**Comment by altavir** [comment]
Проблема не только в overleaf.
Фиксится вставкой    ` \pagenumbering{arabic}` после ` \titlecontents`

**Comment by yl3dy** [comment]
Я думал о подобном фиксе. А где еще проявляется эта проблема?

**Comment by altavir** [comment]
Ну если неправильные нумера страниц, то они и в оглавлении неправильные. Если вставлять команду перед титулом, то она не помогает. Я думаю, что пакет, рисующий титул и оглавление, что-то портит и не восстанавливает.

**Comment by yl3dy** [comment]
Я имею ввиду, с помощью чего вы тестировали, кроме Overleaf? Xelatex, lualatex, что-то еще?

**Comment by altavir** [comment]
pdflatex на локалке. На Lua ожидаемо ничего не работает, поскольку там надо руками русские юникод шрифты прописывать.

Чтобы работало надо добавлять что-то вроде вот этого:
```latex
\ifluatex
	%%% Language setting for (xe|lua)latex %%%
	\RequirePackage{unicode-math}
	\RequirePackage{polyglossia}
	\setdefaultlanguage[spelling=modern]{russian}
	\setotherlanguage{english}
	\setmainfont{CMU Serif}
	\setsansfont{CMU Sans Serif}
	\setmonofont{CMU Typewriter Text}
	\setmathfont{Latin Modern Math}

	\frenchspacing
\else
	%	\RequirePDFTeX % Tests for PDFTEX use and throws an error if a different engine is being used.

	%%% For proper copypasting of text from pdf %%%
	\usepackage{cmap} % Better search and copypasting of cyrillic text from pdf-file. Can cause errors if used together with pdfx package.
	\defaulthyphenchar=127 % Better hyphenation for copypasting. Must be set just before fontenc.

	%%% Language setting for pdflatex %%%
	\usepackage[T2A]{fontenc}
	\usepackage[utf8]{inputenc}
	\usepackage[russian]{babel}
	\RequirePackage{soulutf8}
        \RequirePackage{mathtext} % кириллица в формулах
\fi

```
только шрифты брать более стандартные.

**Comment by yl3dy** [comment]
Хм, про pdflatex интересно. У меня с Texlive 2014 из Debian 8 дефолт был на \pagenumbering{arabic}, возможно в более поздних версиях поменяли. Завтра попробую пофиксить и потестировать.

**Comment by yl3dy** [comment]
Кажется, я нашел простое решение. Пример из документации был не полон: чтобы стиль book правильно работал, перед основной частью надо указывать \mainmatter. Тогда с нумерацией проблем совсем не будет.

**Comment by yl3dy** [comment]
Пример и документация обновлены в 40ba19e
